version: '3'
services:
  server:
    container_name: jet
    image: hazelcast/hazelcast-jet:4.3
    volumes:
      - /Users/nico/.m2/repository:/opt/hazelcast/classpath
      - /Users/nico/projects/hazelcast/jet-train:/opt/hazelcast/data
    ports:
      - 5701:5701
    environment:
      - MIN_HEAP_SIZE=1G
      - CLASSPATH=/opt/hazelcast/classpath/org/json/json/20200518/json-20200518.jar:/opt/hazelcast/classpath/org/jetbrains/kotlin/kotlin-stdlib/1.4.10/kotlin-stdlib-1.4.10.jar:/opt/hazelcast/classpath/com/github/kittinunf/fuel/fuel/2.3.0/fuel-2.3.0.jar:/opt/hazelcast/classpath/com/github/kittinunf/result/result/3.1.0/result-3.1.0.jar
      - JAVA_OPTS=-Xmx18g -XX:+UseStringDeduplication
  webapp:
    container_name: webapp
    image: hazelcast/jettrain:latest
    volumes:
      - /Users/nico/projects/hazelcast/jet-train/infrastructure/etc:/etc/jettrain
    ports:
      - 8080:8080
    depends_on:
      - server
  management-center:
    container_name: jet-management-center
    image: hazelcast/hazelcast-jet-management-center:4.3
    volumes:
      - /Users/nico/projects/hazelcast/jet-train/infrastructure/etc:/opt/hazelcast/etc
    ports:
      - 8081:8081
    environment:
      - MC_CLIENT_CONFIG=/opt/hazelcast/etc/hazelcast-client.xml
    depends_on:
      - server
