version: '3'
services:
  server:
    container_name: jet
    image: hazelcast/hazelcast-jet:4.0
    volumes:
      - /Users/nico/.m2/repository:/opt/hazelcast/classpath
      - /Users/nico/projects/hazelcast/jet-train/infrastructure/data:/opt/hazelcast/data
    environment:
      - MIN_HEAP_SIZE=1G
      - CLASSPATH=/opt/hazelcast/classpath/org/json/json/20190722/json-20190722.jar:/opt/hazelcast/classpath/org/jetbrains/kotlin/kotlin-stdlib/1.3.50/kotlin-stdlib-1.3.50.jar:/opt/hazelcast/classpath/com/github/kittinunf/fuel/fuel/2.2.1/fuel-2.2.1.jar:/opt/hazelcast/classpath/com/github/kittinunf/result/result/2.2.0/result-2.2.0.jar
      - JAVA_OPTS=-Xmx24g -XX:+UseStringDeduplication
    ports:
      - 5701:5701
  management-center:
    container_name: jet-management-center
    volumes:
      - /Users/nico/projects/hazelcast/jet-train/infrastructure/etc:/opt/hazelcast/etc
    environment:
      - MC_CLIENT_CONFIG=/opt/hazelcast/etc/hazelcast-client.xml
    image: hazelcast/hazelcast-jet-management-center:4.0
    ports:
      - 8081:8081
    depends_on:
      - server
